name: qr_code_project  # The name of your project
description: A Flutter project for generating QR codes.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0" # Specify the Dart SDK version

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0 # QR code generation package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  # Added lint package for analysis

flutter:
  uses-material-design: true
